### ISSUE TITLE
Table Clarification

### ISSUE THREAD

**Issue by jshear95** [ARamsey118/Latex_Tutorial#1]
In latexTut.tex line 287 (shown below), it has a line for creating a multi column setup. The comment just says what it does and does not explain how the line works. Further detail should be proveded in the PDF.

 `\begin{tabular}{lcr} % A multicolum command will span more than one column`

Some suggestions:
- `l`, `c`, `r` are for left right and center formatting respectively
- adding additional `l`,`c`,`r` will create additional columns
- adding `|` (pipe) between the `l`,`c`,`r` will add a vertical bar between the columns

**Comment by ARamsey118** [comment]
Does [this](https://github.com/ARamsey118/Latex_Tutorial/blob/120cf61f122316eafd785940a25ca59ff70b4f01/latexTut.tex#L167-L169) provide enough explanation?

**Comment by jshear95** [comment]
Yes. Awesome! Thanks.

**Comment by ARamsey118** [comment]
You're welcome. Closing
